### ISSUE TITLE
Bug: Failed to open and read environment: no value given for required property text

### ISSUE THREAD

**Issue by dirien** [pulumi/esc-sdk#28]
### What happened?

When using the SDK and read an environment with a value with a colong, I get `2024/10/07 11:50:27 Failed to open and read environment: no value given for required property text`

In my example case it is the value of `pulumiConfig.POSTGRES_IMAGE` which triggers the error. The moment I remove the this field, everything wroks fine and the environment can be read.

### Example

````
imports:
  - voting-app/base
values:
  labels:
    component: db
  postgres:
    replicas: 1
    image:
      name: postgres
      tag: 15-alpine
    port: 5432
    user: postgres
    password:
      fn::secret:
        ciphertext: ZXNjeAAAAAEAAAEA4YnCWhF6SR/Jhk0GfvDLRlW7ZhV3cexS47JdODiP22T8WX8KZRU1Lg==
  pulumiConfig:
    POSTGRES_USER: ${postgres.user}
    POSTGRES_PASSWORD: ${postgres.password}
    POSTGRES_PORT: ${postgres.port}
    LABELS: ${labels}
    POSTGRES_IMAGE: ${postgres.image.name}:${postgres.image.tag}
    POSTGRES_REPLICA: ${postgres.replicas}
```

### Output of `pulumi about`

```go
module gotest

go 1.23.1

require github.com/pulumi/esc-sdk/sdk v0.10.0

require (
	gopkg.in/ghodss/yaml.v1 v1.0.0 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
)
```

### Additional context

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
