### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by dirien** [pulumi/esc-sdk#54]
### What happened?

I keep getting on a specific evironment a `2024/11/22 12:58:57 Failed to open and read environment: 400 Bad Request`

I assume it is in environments with an `import` statement.

### Example

Here is an example client go code to test:

```go
package main

import (
	"fmt"
	esc "github.com/pulumi/esc-sdk/sdk/go"
	"log"
	"os"
)

func main() {
	accessToken := os.Getenv("PULUMI_ACCESS_TOKEN")
	projectName := "dirien"
	orgName := "ediri"
	envName := "joke-app"
	configuration := esc.NewConfiguration()
	escClient := esc.NewClient(configuration)
	authCtx := esc.NewAuthContext(accessToken)

	_, values, err := escClient.OpenAndReadEnvironment(authCtx, orgName, projectName, envName)
	if err != nil {
		log.Fatalf("Failed to open and read environment: %v", err)
	}
	fmt.Println(values)
}
```

When the enviroment looks like this:

```yaml
imports:
  - dirien/base
values:
  test:
    name: world
  openapi-key: xxxx
  environmentVariables:
    OPENAI_API_KEY: ${openapi-key}
```

I get following error:

```bash
➜ go run .
2024/11/22 13:04:41 Failed to open and read environment: 400 Bad Request
exit status 1
````

When. removing the:

````yaml
values:
  test:
    name: world
  openapi-key: xxxx
  environmentVariables:
    OPENAI_API_KEY: ${openapi-key}
````

And run again:

```bash
go run .
map[environmentVariables:map[OPENAI_API_KEY:xxx] openapi-key:xxx test:map[name:world]]
````

it works

The base looks like this:

```yaml
values:
  environmentVariables:
    AWS_ACCESS_KEY_ID: ${aws.creds.accessKeyId}
    AWS_SECRET_ACCESS_KEY: ${aws.creds.secretAccessKey}
    AWS_SESSION_TOKEN: ${aws.creds.sessionToken}
    AWS_REGION: ${aws.region}
  aws:
    region: eu-central-1
    creds:
      fn::open::aws-login:
        oidc:
          roleArn: arn:aws:iam::052848974346:role/pulumi-demo-org-deployments-oidc
          sessionName: pulumi-environments-session
          duration: 1h
```

The issue is when using ```fn::open::aws-login```. If I remove this line it works fine again.

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
